### ISSUE TITLE
error

### ISSUE THREAD

**Issue by a5x** [accompts/Roblox-Account-Generator#1]
Yo i have this error, 
![image](https://github.com/accompts/Roblox-Account-Generator/assets/134241855/c07f5f84-ee81-4671-9f8f-69750c669bfd)

and after i remove this line i have this too ;

![image](https://github.com/accompts/Roblox-Account-Generator/assets/134241855/376ee93e-51f2-46f5-a8b1-cbe4d59e27cd)

**Comment by ghost** [comment]
pip install requests 🧠

**Comment by a5x** [comment]
> pip install requests 🧠

all ready installed

**Comment by accompts** [comment]
fixed my bad
